name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Docker Build
        run:  docker build -t version-cicd .
      - name: Docker change Tag
        run : docker tag version-cicd ${{ secrets.DOCKER_HUB_USERNAME }}/version-cicd:${GITHUB_SHA::7}
      - name: Docker Push
        run : docker push ${{ secrets.DOCKER_HUB_USERNAME }}/version-cicd:${GITHUB_SHA::7}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/version-cicd:${GITHUB_SHA::7}
            docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/version-cicd:${GITHUB_SHA::7} version-cicd
            docker stop server
            docker rm -f server
            docker run -d --name server -p 8080:8080 version-cicd